In [1]:
# from ultralytics import YOLO
# model = YOLO("yolov8n-seg")
# results = model.train(data="breast_cancer_dataset.yaml", epochs=100, imgsz=320,device="cuda",workers = 8, cache = "disk", amp = True,patience=25,batch=16)

In [2]:
# from ultralytics import YOLO
# model = YOLO("yolov8s-seg")
# results = model.train(data="breast_cancer_dataset.yaml", epochs=100, imgsz=320,device="cuda",workers = 8, cache = "disk", amp = True,patience=25,batch=16)

In [3]:
# from ultralytics import YOLO
# model = YOLO("yolo11n-seg")
# results = model.train(data="breast_cancer_dataset.yaml", epochs=100, imgsz=320,device="cuda",workers = 8, cache = "disk", amp = True,patience=25,batch=16)

In [4]:
# from ultralytics import YOLO
# model = YOLO("yolov8m-seg")
# results = model.train(data="breast_cancer_dataset.yaml", epochs=100, imgsz=320,device="cuda",workers = 8, cache = "disk", amp = True,patience=25,batch=16)

In [10]:
import pandas as pd
data = pd.read_csv("../dataset/breast-cancer.csv")
X = data.iloc[:,2:].values
Y = data.iloc[:,1].values

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)
print(Y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)

from sklearn.preprocessing import StandardScaler
x_scaler = StandardScaler()
x_train = x_scaler.fit_transform(x_train)
x_test = x_scaler.transform(x_test)

from sklearn.svm import SVC
classifier = SVC(kernel="rbf")
classifier.fit(x_train,y_train)

predicitions = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predicitions))
print(accuracy_score(y_test,predicitions))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

In [7]:
import tensorflow as tf

ann = tf.keras.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=1,activation="relu"))

ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

# ann.fit(x=x_train,y=y_train,epochs=100,batch_size=32)
# ann.save("breast_cancer_model.keras")

ann = tf.keras.models.load_model("breast_cancer.keras")

predicitions = ann.predict(x_test)
predicitions = predicitions > 0.5
print(confusion_matrix(y_test,predicitions))
print(accuracy_score(predicitions,y_test))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[[68  0]
 [ 6 40]]
0.9473684210526315


In [8]:
data = pd.read_csv("../dataset/breast-cancer.csv")
X = data.iloc[:,2:].values
Y = data.iloc[:,1].values
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

predicitions = classifier.predict(x_test)
print(confusion_matrix(y_test,predicitions))
print(accuracy_score(predicitions,y_test))

[[61  4]
 [ 5 44]]
0.9210526315789473


In [9]:
data = pd.read_csv("../dataset/breast-cancer.csv")
X = data.iloc[:,2:].values
Y = data.iloc[:,1].values

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)

from sklearn.preprocessing import StandardScaler
x_scaler = StandardScaler()
x_train = x_scaler.fit_transform(x_train)
x_test = x_scaler.transform(x_test)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(x_train,y_train)

predicitions = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predicitions))
print(accuracy_score(y_test,predicitions))

[[76  1]
 [ 5 32]]
0.9473684210526315
